name: Docker Image CI

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
      
    - id: get_repository
      run: echo ::set-output name=NAME::${GITHUB_REPOSITORY#*/}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: seekie/${{ steps.get_repository.outputs.NAME }}:latest,seekie/${{ steps.get_repository.outputs.NAME }}:${{ steps.get_version.outputs.VERSION }}
